<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">';
echo '<title>PG Gallery</title>';
echo '<link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">';
echo '<link rel="stylesheet" href="assets/fonts/ionicons.min.css">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar gradient">';
echo '<div class="container"><a class="navbar-brand logo" href="#">PG Accommodation Management</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navbarNav"><span class="sr-only"></span></button>';
echo '<div class="collapse navbar-collapse" id="navbarNav">';
echo '<ul class="navbar-nav ml-auto">';
echo '<li class="nav-item"></li>';
echo '<li class="nav-item"></li>';
echo '<li class="nav-item"></li>';
echo '<li class="nav-item"></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '<main class="page projects-page">';
echo '<section class="portfolio-block projects-cards">';
echo '<div class="container">';
echo '<div class="heading">';
echo '<h2>Hello!</h2>';
echo '</div>';
echo '';
echo '';
echo '<div>';
echo '<section class="portfolio-block block-intro">';
echo '<div class="container">';
echo '<div class="about-me">';
echo '<p>If you are looking for a PG who offer&nbsp;three meals a day, along with spacious rooms and essential furniture, common entertainment and leisure areas and even have maintenance staff to attend to the daily chores. <br>If you are looking for an affordable rental PG rooms then click on the link below<br></p><a class="btn btn-outline-primary" role="button" href="https://localhost/hostel_mgmt/hostel/registration.php">Register&nbsp;</a>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div class="row">';
echo '<div class="col-md-6 col-lg-4">';
echo '<div class="card border-0"><a href="#"><img class="card-img-top scale-on-hover" src="assets/img/nature/3.jpg" alt="Card Image"></a>';
echo '<div class="card-body">';
echo '<h6><a href="#"></a></h6>';
echo '<p class="text-muted card-text"></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4">';
echo '<div class="card border-0"><a href="#"><img class="card-img-top scale-on-hover" src="assets/img/nature/1.jpg" alt="Card Image" style="height: 240px"></a>';
echo '<div class="card-body">';
echo '<h6><a href="#"></a></h6>';
echo '<p class="text-muted card-text"></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4">';
echo '<div class="card border-0"><a href="#"><img class="card-img-top scale-on-hover" src="assets/img/nature/5.jpg" alt="Card Image" style="height: 220px"></a>';
echo '<div class="card-body">';
echo '<h6><a href="#"></a></h6>';
echo '<p class="text-muted card-text"></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4">';
echo '<div class="card border-0"><a href="#"><img class="card-img-top scale-on-hover" src="assets/img/nature/6.jpg" alt="Card Image" style="height: 240px"></a>';
echo '<div class="card-body">';
echo '<h6><a href="#"></a></h6>';
echo '<p class="text-muted card-text"></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4">';
echo '<div class="card border-0"><a href="#"><img class="card-img-top scale-on-hover" src="assets/img/nature/2.jpg" alt="Card Image" style="height: 240px"></a>';
echo '<div class="card-body">';
echo '<h6><a href="#"></a></h6>';
echo '<p class="text-muted card-text"></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4">';
echo '<div class="card border-0"><a href="#"><img class="card-img-top scale-on-hover" src="assets/img/nature/4.jpg" alt="Card Image" style="height: 240px"></a>';
echo '<div class="card-body">';
echo '<h6><a href="#"></a></h6>';
echo '<p class="text-muted card-text"></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '</main>';
echo '<footer class="page-footer"></footer>';
echo '<script src="assets/js/jquery.min.js"></script>';
echo '<script src="assets/bootstrap/js/bootstrap.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>';
echo '<script src="assets/js/theme.js"></script>';
echo '</body>';
echo '';
echo '</html>';
?>